server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container:
      name: ${PROD_CONTAINER}
