server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container:
      name: ${DEV_CONTAINER}
